[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[env]
  EMAILJS_USER_ID = "41-7Oca3QhFUFlQpB"
  EMAILJS_ACCESS_TOKEN = "p0FkQTv3aAVdjCDiTTKKU"
  EMAILJS_SERVICE_TOKEN = "service_xm6a5er"
  EMAILJS_TEMPLATE_TOKEN = "template_zyy5mrf"